### ISSUE TITLE
colab notebook

### ISSUE THREAD

**Issue by boumpteryx** [IkeYang/ViTime#1]
Hello, Could you please provide a colab notebook for quick testing your model on custom data?

**Comment by IkeYang** [comment]
Hello,

We have prepared a quick start file for testing our model on custom data in Colab. You can access it through the following link:

[Colab Quick Start File](https://colab.research.google.com/drive/1vWi2razIF58TOm1SDG3bwyPb_I8qMRXh?usp=sharing)

Welcome to use it, and feel free to reach out if you have any questions!

Let me know if there's anything else I can help with!

Luoxiao
